
// This file has been generated by the GUI designer. Do not modify.
namespace Notepad
{
	public partial class NotepadView
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action saveAction;
		private global::Gtk.Action saveAsAction;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action quitAction;
		private global::Gtk.Action EditAction;
		private global::Gtk.Action ViewAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Action saveAction1;
		private global::Gtk.Action saveAsAction1;
		private global::Gtk.Action openAction;
		private global::Gtk.Action newAction;
		private global::Gtk.Action openAction1;
		private global::Gtk.Action filesaveAction;
		private global::Gtk.Action filesaveAsAction;
		private global::Gtk.ToggleAction statusBarAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textBody;
		private global::Gtk.Statusbar statusbar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Notepad.NotepadView
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
			w1.Add (this.saveAction, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, null, "gtk-save-as");
			w1.Add (this.saveAsAction, null);
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.quitAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
			this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
			w1.Add (this.ViewAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.saveAction1 = new global::Gtk.Action ("saveAction1", null, null, "gtk-save");
			this.saveAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
			w1.Add (this.saveAction1, null);
			this.saveAsAction1 = new global::Gtk.Action ("saveAsAction1", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
			this.saveAsAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
			w1.Add (this.saveAsAction1, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
			w1.Add (this.openAction, null);
			this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("_New"), null, "gtk-new");
			this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
			w1.Add (this.newAction, null);
			this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
			this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
			w1.Add (this.openAction1, null);
			this.filesaveAction = new global::Gtk.Action ("filesaveAction", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
			this.filesaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
			w1.Add (this.filesaveAction, null);
			this.filesaveAsAction = new global::Gtk.Action ("filesaveAsAction", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
			this.filesaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
			w1.Add (this.filesaveAsAction, null);
			this.statusBarAction = new global::Gtk.ToggleAction ("statusBarAction", global::Mono.Unix.Catalog.GetString ("Status Bar"), null, null);
			this.statusBarAction.Active = true;
			this.statusBarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Status Bar");
			w1.Add (this.statusBarAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Notepad.NotepadView";
			this.Title = global::Mono.Unix.Catalog.GetString ("NotepadView");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.LargeToolbar);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(2));
			// Container child Notepad.NotepadView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction1' action='openAction1'/><separator/><menuitem name='filesaveAction' action='filesaveAction'/><menuitem name='filesaveAsAction' action='filesaveAsAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditAction' action='EditAction'/><menu name='ViewAction' action='ViewAction'><menuitem name='statusBarAction' action='statusBarAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textBody = new global::Gtk.TextView ();
			this.textBody.CanFocus = true;
			this.textBody.Name = "textBody";
			this.textBody.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.textBody);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar = new global::Gtk.Statusbar ();
			this.statusbar.Name = "statusbar";
			this.statusbar.Spacing = 6;
			this.vbox1.Add (this.statusbar);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 635;
			this.DefaultHeight = 381;
			this.Show ();
			this.statusBarAction.Toggled += new global::System.EventHandler (this.ontoggleStatusbarAction);
		}
	}
}
